x-environment-defaults: &environment-defaults
  SECRET_KEY: "wow, i`m a very secret password"
  EMAIL_HOST: "smtp.mail.ru"
  EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  EMAIL_PORT: "465"
  EMAIL_HOST_USER: "example@gmail.com"
  EMAIL_HOST_PASSWORD: "email.host.password"
  DB_PASSWORD: "db_password"
  DB_USER: "db_user"
  DB_NAME: "db_name"
  DB_HOST: "db"
  DB_PORT: 5432
  CELERY_BROKER_URL: "redis://redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis:6379/0"
  DEBUG: "False"

version: '3'
services:

  server:
    build: .
    ports:
      - "8000:8000"
    container_name: django-server
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db
    networks:
      - chat-network
    environment:
      <<: *environment-defaults

  db:
    image: postgres:16.0-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - chat-network

  nginx:
    image: nginx:1.25.3-alpine-slim
    container_name: nginx-container
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
      - media_volume:/media
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - chat-network

  redis:
    image: redis:7.2.2-alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - chat-network

  celery:
    build:
      context: .
    command: celery -A chat worker --loglevel=info
    container_name: celery-container
    depends_on:
      - redis
      - db
    volumes:
      - .:/app
    environment:
      <<: *environment-defaults
    networks:
      - chat-network

  celery-beat:
    build:
      context: .
    container_name: celery-beat-container
    command: celery -A chat beat --loglevel=info
    depends_on:
      - redis
      - db
      - celery
    volumes:
      - .:/app
    environment:
      <<: *environment-defaults
    networks:
      - chat-network

volumes:
  pg_data:
  static_volume:
  media_volume:

networks:
  chat-network:
    driver: bridge