# Generated by Django 4.2.5 on 2023-09-28 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0002_notificationtypes_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notify_room', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Avatar',
            field=models.ImageField(null=True, upload_to='images/users-avatars/'),
        ),
    ]
