# Generated by Django 4.2.5 on 2023-09-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0003_notifications_user_alter_customuser_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.DeleteModel(
            name='NotificationTypes',
        ),
    ]
