# Generated by Django 4.2.5 on 2023-10-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0004_delete_notifications_delete_notificationtypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Date_of_birth',
            field=models.DateField(),
        ),
    ]
