# Generated by Django 4.2.5 on 2023-10-02 12:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0005_alter_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='users_read',
            field=models.ManyToManyField(related_name='users_read', to=settings.AUTH_USER_MODEL),
        ),
    ]
