# Generated by Django 4.2.5 on 2023-10-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0007_alter_room_image_direct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direct',
            name='image',
            field=models.ImageField(null=True, upload_to='images/direct-images/'),
        ),
    ]
