# Generated by Django 4.2.5 on 2023-10-03 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0008_alter_direct_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='new_folder', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('chat', 'chat'), ('direct', 'direct')], default='direct', max_length=6),
        ),
        migrations.DeleteModel(
            name='Direct',
        ),
        migrations.AddField(
            model_name='folder',
            name='rooms',
            field=models.ManyToManyField(related_name='folder_rooms', to='chat_api.room'),
        ),
        migrations.AddField(
            model_name='folder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_folder', to=settings.AUTH_USER_MODEL),
        ),
    ]
