# Generated by Django 4.2.5 on 2023-10-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0009_folder_room_type_delete_direct_folder_rooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(default='unknown_room', unique=True),
        ),
    ]
