# Generated by Django 4.2.5 on 2023-10-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0011_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Avatar',
            field=models.ImageField(default='images/users-avatars/base-user.png', null=True, upload_to='images/users-avatars/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(default='images/room-images/base-room.png', null=True, upload_to='images/room-images/'),
        ),
    ]
