# Generated by Django 4.2.6 on 2023-10-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0013_alter_customuser_avatar_alter_room_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'verbose_name': 'Folder', 'verbose_name_plural': 'Folder'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-sent_at',), 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Date_of_birth',
            field=models.DateField(auto_now_add=True),
        ),
    ]
